[platformio]
default_envs = maestro, esclavo

[env:maestro]
platform = espressif32 @ ^6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<maestro/> -<esclavo/>  ; Compila solo lo que esté en src/maestro
upload_port = COM4                          ; El puerto físico de tu ESP32 Maestro
lib_deps =
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    miguelbalboa/MFRC522 @ ^1.4.11
    chris--a/Keypad @ ^3.1.1

[env:esclavo]
platform = espressif32 @ ^6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<esclavo/> -<maestro/>  ; Compila solo lo que esté en src/esclavo
upload_port = COM3                          ; El puerto físico de tu ESP32 Esclavo (el viejo)
lib_deps =
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    miguelbalboa/MFRC522 @ ^1.4.11
    chris--a/Keypad @ ^3.1.1